[project]
name = 'open-gov'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.delegate-voting]
path = 'contracts/delegate-voting.clar'
clarity_version = 2
epoch = 2.1

[contracts.events-create]
path = 'contracts/events-create.clar'
clarity_version = 2
epoch = 2.1

[contracts.events-dislike]
path = 'contracts/events-dislike.clar'
clarity_version = 2
epoch = 2.1

[contracts.events-like]
path = 'contracts/events-like.clar'
clarity_version = 2
epoch = 2.1

[contracts.fund-treasury-pool]
path = 'contracts/fund-treasury-pool.clar'
clarity_version = 2
epoch = 2.1

[contracts.open-gov]
path = 'contracts/open-gov.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
