[project]
name = 'open-gov'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.create-event]
path = 'contracts/create-event.clar'
clarity_version = 2
epoch = 2.1

[contracts.dislike-events]
path = 'contracts/dislike-events.clar'
clarity_version = 2
epoch = 2.1

[contracts.like-events]
path = 'contracts/like-events.clar'
clarity_version = 2
epoch = 2.1

[contracts.open-gov]
path = 'contracts/open-gov.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
